name: Build

on:
  push:
    branches:
      - sweng-back
  pull_request:
    branches:
      - sweng-back

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List contents of the root directory
        run: ls

      - name: Change to backend/demo directory
        run: cd backend/demo

      - name: List contents of the backend/demo directory
        run: ls

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Adjust as needed
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn spring-boot:run
